language: java

sudo: false

jdk:
  - oraclejdk8

##
# When a release is tagged, push to GitHub Releases.
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN 
  file: ./build/libs/storm-websockets.jar
  skip_cleanup: true
  on:
    tags: true
